; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_untitled=music_data_untitled
.endif

music_data_untitled:
	.byte 5
	.word @instruments
	.word @samples-52
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : Outside
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4 ; 01 : Indoors
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4 ; 02 : Title
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4 ; 03 : GameOver
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4 ; 04 : Howl
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Instrument 1

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$05,$40	;13 (game)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;14 
	.byte $05+.lobyte(FAMISTUDIO_DPCM_PTR),$24,$00,$00	;15 (howl)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;16 
	.byte $0f+.lobyte(FAMISTUDIO_DPCM_PTR),$1a,$05,$40	;17 (over)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;18 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;19 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;20 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;21 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;22 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;23 
	.byte $05+.lobyte(FAMISTUDIO_DPCM_PTR),$24,$03,$00	;24 (howl)

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref5:
	.byte $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47
	.byte $41, $12
	.word @song0ref5
	.byte $47, $ff, $ff, $bf, $47, $80, $3a, $a5, $00, $a5, $3a, $a5, $00, $a5, $3a, $a5, $00, $a5, $3a, $a5, $00, $a5, $47, $ff
	.byte $ff, $bf, $47, $3a, $a5, $00, $a5, $3a, $91, $00, $91, $3a, $91, $00, $91, $3a, $91, $00, $91, $3a, $91, $00, $91, $3a
	.byte $a5, $00, $a5, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $ff, $ff, $bf, $80
@song0ref99:
	.byte $19, $cd, $1b, $cd, $19, $a5, $1b, $a5, $1d, $a5, $19, $91, $00, $91, $1b, $91, $1d, $91, $1b, $91, $1d, $91, $00, $cd
	.byte $1b, $91, $1d
@song0ref126:
	.byte $91, $1b, $91, $1d, $91, $00, $cd, $19, $b9, $00, $91, $1b, $cd, $19, $a5, $1b, $a5, $1e, $a5, $1d, $a5, $1b, $91, $00
	.byte $91, $1b, $91, $19, $91, $1b, $cd, $00, $91, $19, $91, $00, $91, $1b, $91, $1e, $cd, $00, $ff, $ff, $bd, $ff, $ff, $bf
	.byte $ff, $ff, $bf
	.byte $41, $10
	.word @song0ref99
	.byte $19, $91, $1b, $91, $1d, $91, $00, $cd, $1b, $91, $19
	.byte $41, $16
	.word @song0ref126
	.byte $cd, $19, $91, $00, $91, $1b, $91, $00, $91, $1d, $a5, $1e, $a5, $1b, $a5, $1d, $91, $1b, $91, $00, $ff, $ff, $bd, $1b
	.byte $a5, $00, $a5, $1b, $a5, $00, $a5, $1b, $a5, $00, $a5
@song0ref229:
	.byte $1b, $a5, $00, $a5, $1b, $a5, $1d, $91, $1b, $91, $00, $cd, $1b, $a5, $1d, $91, $1b, $91, $00, $cd, $1b, $a5, $00, $a5
	.byte $1b, $91, $00, $91, $1b, $91, $00, $91, $1b, $91, $00, $91, $1b, $91, $00, $91
	.byte $41, $14
	.word @song0ref229
	.byte $ff, $ff, $bf, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref280:
	.byte $1b, $c1, $00, $d9, $19, $c1, $00, $9d, $19, $8f, $00, $81, $1b, $8d, $00, $19, $87, $00, $87
	.byte $41, $13
	.word @song0ref280
	.byte $41, $13
	.word @song0ref280
	.byte $41, $13
	.word @song0ref280
	.byte $41, $13
	.word @song0ref280
	.byte $41, $13
	.word @song0ref280
	.byte $ff, $ff, $bf
	.byte $41, $13
	.word @song0ref280
	.byte $41, $13
	.word @song0ref280
	.byte $41, $13
	.word @song0ref280
	.byte $41, $13
	.word @song0ref280
	.byte $41, $13
	.word @song0ref280
	.byte $41, $13
	.word @song0ref280
	.byte $41, $13
	.word @song0ref280
	.byte $41, $13
	.word @song0ref280
	.byte $41, $13
	.word @song0ref280
	.byte $41, $13
	.word @song0ref280
	.byte $41, $13
	.word @song0ref280
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $80
@song0ref355:
	.byte $24, $91, $00, $91, $24, $87, $00, $9b, $22, $91, $00, $a5, $22, $89, $00, $85, $24, $91, $00, $91, $24, $87, $00, $9b
	.byte $22, $8f, $00, $bb
	.byte $41, $1c
	.word @song0ref355
	.byte $41, $1c
	.word @song0ref355
	.byte $41, $1c
	.word @song0ref355
	.byte $41, $1c
	.word @song0ref355
	.byte $41, $1c
	.word @song0ref355
	.byte $41, $1c
	.word @song0ref355
	.byte $41, $1c
	.word @song0ref355
	.byte $41, $1c
	.word @song0ref355
	.byte $41, $1c
	.word @song0ref355
	.byte $41, $1c
	.word @song0ref355
	.byte $41, $1c
	.word @song0ref355
	.byte $41, $1c
	.word @song0ref355
	.byte $41, $1c
	.word @song0ref355
	.byte $41, $1c
	.word @song0ref355
	.byte $41, $1c
	.word @song0ref355
	.byte $41, $1c
	.word @song0ref355
	.byte $41, $1c
	.word @song0ref355
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref438:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $12
	.word @song0ref438
	.byte $41, $12
	.word @song0ref438
	.byte $42
	.word @song0ch4loop
@song1ch0:
@song1ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $bf, $47, $80, $2e, $cd, $30, $a5, $31, $a5, $35
	.byte $a5, $33, $91, $35, $91, $2e, $b9, $00, $91, $47, $2e, $cd, $31, $a5, $30, $a5, $31, $cd, $2e, $b9, $00, $91, $47, $2e
	.byte $cd, $30, $a5, $31, $a5, $33, $a5, $35, $91, $33, $91, $2e, $b9, $00, $91, $47, $2e, $91, $30, $91, $2e, $a5, $30, $91
	.byte $31, $91, $33, $91, $35, $91, $00, $91, $35, $91, $00, $91, $35, $91, $2e, $b9, $00, $91, $47, $ff, $ff, $bf
@song1ref87:
	.byte $47, $2e, $cd, $30, $cd, $31, $a5, $33, $a5, $35
@song1ref97:
	.byte $b9, $00, $91, $47, $35, $cd, $33, $91, $31, $91, $30, $91, $00, $91, $30, $cd, $2e
	.byte $41, $10
	.word @song1ref97
@song1ref117:
	.byte $b9, $00, $91, $47, $30, $cd, $2e, $91, $30, $91, $2e, $91, $00, $91, $2e, $a5, $31, $91, $33, $91, $2e, $b9, $00, $91
	.byte $41, $19
	.word @song1ref87
	.byte $41, $17
	.word @song1ref117
	.byte $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $ff, $ff, $bf, $80, $1b, $cd, $1d, $a5, $1e, $a5, $22, $a5, $20, $91, $22, $91, $1b, $b9, $00, $91, $1b, $cd, $1e, $a5
	.byte $1d, $a5, $1e, $cd, $1b, $b9, $00, $91, $1b, $cd, $1d, $a5, $1e, $a5, $20, $a5, $22, $91, $20, $91, $1b, $b9, $00, $91
	.byte $1b, $91, $1d, $91, $1b, $a5, $1d, $91, $1e, $91, $20, $91, $22, $91, $00, $91, $22, $91, $00, $91, $22, $91, $1b, $b9
	.byte $00, $91, $ff, $ff, $bf
@song1ref228:
	.byte $1b, $cd, $1d, $cd, $1e, $a5, $20, $a5, $22
@song1ref237:
	.byte $b9, $00, $91, $22, $cd, $20, $91, $1e, $91, $1d, $91, $00, $91, $1d, $cd, $1b
	.byte $41, $10
	.word @song1ref237
@song1ref256:
	.byte $b9, $00, $91, $1d, $cd, $1b, $91, $1d, $91, $1b, $91, $00, $91, $1b, $a5, $1e, $91, $20, $91, $1b, $b9, $00, $91
	.byte $41, $19
	.word @song1ref228
	.byte $41, $17
	.word @song1ref256
	.byte $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $80, $1b, $a5, $00, $a5, $1b, $a5, $00, $a5, $1b, $a5, $00, $a5, $1b, $a5, $00, $a5
@song1ref306:
	.byte $1b, $91, $00, $e1, $1b, $91, $00, $91, $1b, $91, $00, $b9, $1b, $91, $00, $b9, $1d, $91, $00, $b9, $1d, $91, $00, $b9
	.byte $1b, $91, $00, $b9, $1b, $91, $00, $b9
	.byte $41, $13
	.word @song1ref306
	.byte $91, $1d, $91, $00, $91, $1b, $91, $00, $91, $1b, $91, $00, $91, $1d, $91, $00, $91, $1d, $91, $00, $91, $1d, $91, $00
	.byte $b9
@song1ref366:
	.byte $18, $b9, $00, $91
@song1ref370:
	.byte $19, $91, $00, $91, $19, $91, $00, $91, $19, $91, $00, $91, $19, $91, $00, $91, $18, $b9, $00, $91, $18, $b9, $00, $91
	.byte $18, $b9, $00, $91, $18, $91, $00, $91, $18, $91, $00, $91, $19, $b9, $00, $91
	.byte $41, $1c
	.word @song1ref366
	.byte $41, $18
	.word @song1ref370
	.byte $41, $28
	.word @song1ref370
	.byte $41, $1c
	.word @song1ref366
	.byte $41, $14
	.word @song1ref370
	.byte $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $80
@song1ref430:
	.byte $24, $91, $00, $91
@song1ref434:
	.byte $24, $91, $00, $91, $20, $91, $00, $91, $20, $91, $00, $91, $20, $91, $00, $b9, $24, $91, $00
@song1ref453:
	.byte $b9
@song1ref454:
	.byte $24, $91, $00, $91, $22
@song1ref459:
	.byte $91, $00, $91, $22, $91, $00, $91, $24, $91, $00, $91
	.byte $41, $0b
	.word @song1ref454
	.byte $41, $11
	.word @song1ref453
	.byte $41, $0b
	.word @song1ref454
	.byte $41, $11
	.word @song1ref453
	.byte $41, $0b
	.word @song1ref454
	.byte $b9, $24
	.byte $41, $0b
	.word @song1ref459
	.byte $22, $91, $00, $91
	.byte $41, $0b
	.word @song1ref454
	.byte $b9
	.byte $41, $1c
	.word @song1ref430
	.byte $41, $18
	.word @song1ref434
	.byte $41, $18
	.word @song1ref434
	.byte $41, $18
	.word @song1ref434
	.byte $41, $18
	.word @song1ref434
	.byte $41, $18
	.word @song1ref434
	.byte $41, $18
	.word @song1ref434
	.byte $41, $14
	.word @song1ref434
	.byte $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref526:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0c
	.word @song1ref526
	.byte $41, $0c
	.word @song1ref526
	.byte $ff, $ff, $bf, $42
	.word @song1ch4loop
@song2ch0:
@song2ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $80
@song2ref14:
	.byte $0c, $cd, $0f, $cd, $11, $cd, $0c, $b9, $00, $91, $47, $11, $cd, $0f, $cd, $0c, $cd, $0f, $b9, $00, $91, $47
	.byte $41, $14
	.word @song2ref14
	.byte $47, $ff, $ff, $bf, $47, $ff, $ff, $bf
@song2ref47:
	.byte $47, $0c, $cd, $0f, $a5, $10, $a5, $11, $cd, $0c, $b9, $00, $91, $47, $11, $cd, $0f, $a5, $0e, $a5, $0c, $a5, $00, $91
	.byte $0c, $91, $0f, $b9, $00, $91
	.byte $41, $1c
	.word @song2ref47
	.byte $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $80
@song2ref85:
	.byte $05, $cd, $08, $cd, $0a, $cd, $05, $b9, $00, $91, $0a, $cd, $08, $cd, $05, $cd, $08, $b9, $00, $91
	.byte $41, $14
	.word @song2ref85
	.byte $41, $14
	.word @song2ref85
@song2ref111:
	.byte $05, $cd, $08, $a5, $09, $a5, $0a, $cd, $05, $b9, $00, $91, $0a, $cd, $08, $a5, $07, $a5, $05, $a5, $00, $91, $05, $91
	.byte $08, $b9, $00, $91
	.byte $41, $1c
	.word @song2ref111
	.byte $41, $1c
	.word @song2ref111
	.byte $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $80
@song2ref150:
	.byte $08, $b9, $00, $91, $0c, $b9, $00, $91, $43, $0d, $b9, $00, $91, $08, $b9, $00, $91, $0d, $b9, $00, $91, $0c, $b9, $00
	.byte $91, $08, $b9, $00, $91, $0c, $b9, $00, $91
	.byte $41, $20
	.word @song2ref150
	.byte $41, $20
	.word @song2ref150
@song2ref189:
	.byte $11, $91, $00, $91, $11, $91, $00, $91, $11, $91, $00, $91, $11, $91, $00, $91
	.byte $41, $10
	.word @song2ref189
	.byte $41, $10
	.word @song2ref189
	.byte $41, $10
	.word @song2ref189
	.byte $41, $10
	.word @song2ref189
	.byte $41, $10
	.word @song2ref189
	.byte $41, $10
	.word @song2ref189
	.byte $41, $10
	.word @song2ref189
	.byte $41, $10
	.word @song2ref189
	.byte $41, $10
	.word @song2ref189
	.byte $41, $10
	.word @song2ref189
	.byte $41, $10
	.word @song2ref189
	.byte $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
	.byte $ff, $ff, $bf, $80
@song2ref246:
	.byte $24, $91, $00, $91, $24, $91, $00, $91, $22, $91, $00, $b9, $24, $91, $00, $b9, $22, $91, $00, $b9
	.byte $41, $14
	.word @song2ref246
	.byte $41, $14
	.word @song2ref246
	.byte $41, $14
	.word @song2ref246
	.byte $41, $14
	.word @song2ref246
	.byte $41, $14
	.word @song2ref246
	.byte $41, $14
	.word @song2ref246
	.byte $41, $14
	.word @song2ref246
	.byte $41, $14
	.word @song2ref246
	.byte $41, $14
	.word @song2ref246
	.byte $41, $14
	.word @song2ref246
	.byte $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
@song2ref300:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $12
	.word @song2ref300
	.byte $42
	.word @song2ch4loop
@song3ch0:
@song3ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song3ref5:
	.byte $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47
	.byte $41, $0f
	.word @song3ref5
	.byte $47
	.byte $41, $0f
	.word @song3ref5
	.byte $47, $ff, $ff, $bf, $42
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
@song3ref40:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0f
	.word @song3ref40
	.byte $41, $0f
	.word @song3ref40
	.byte $ff, $ff, $bf, $42
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
	.byte $41, $0f
	.word @song3ref40
	.byte $41, $0f
	.word @song3ref40
	.byte $41, $0f
	.word @song3ref40
	.byte $ff, $ff, $bf, $42
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
	.byte $41, $0f
	.word @song3ref40
	.byte $41, $0f
	.word @song3ref40
	.byte $41, $0f
	.word @song3ref40
	.byte $ff, $ff, $bf, $42
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
	.byte $18, $eb, $0d, $c9, $00, $8f, $11, $ef, $00
	.byte $41, $0f
	.word @song3ref40
	.byte $41, $0f
	.word @song3ref40
	.byte $41, $0f
	.word @song3ref40
	.byte $42
	.word @song3ch4loop
@song4ch0:
@song4ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song4ref5:
	.byte $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47
	.byte $41, $0f
	.word @song4ref5
	.byte $47
	.byte $41, $0f
	.word @song4ref5
	.byte $47, $ff, $ff, $bf, $42
	.word @song4ch0loop
@song4ch1:
@song4ch1loop:
@song4ref40:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0f
	.word @song4ref40
	.byte $41, $0f
	.word @song4ref40
	.byte $ff, $ff, $bf, $42
	.word @song4ch1loop
@song4ch2:
@song4ch2loop:
	.byte $41, $0f
	.word @song4ref40
	.byte $41, $0f
	.word @song4ref40
	.byte $41, $0f
	.word @song4ref40
	.byte $ff, $ff, $bf, $42
	.word @song4ch2loop
@song4ch3:
@song4ch3loop:
	.byte $41, $0f
	.word @song4ref40
	.byte $41, $0f
	.word @song4ref40
	.byte $41, $0f
	.word @song4ref40
	.byte $ff, $ff, $bf, $42
	.word @song4ch3loop
@song4ch4:
@song4ch4loop:
	.byte $0f, $ff, $9d, $00, $ff, $9d
	.byte $41, $0f
	.word @song4ref40
	.byte $41, $0f
	.word @song4ref40
	.byte $41, $0f
	.word @song4ref40
	.byte $42
	.word @song4ch4loop
