; This file for the FamiStudio Sound Engine and was generated by FamiStudio


music_data_untitled:
    .byte 1
    .word @instruments
    .word @samples-4
    .word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : Song 1
    .byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
    .word @env1,@env2,@env3,@env0 ; 00 : Instrument 1

@samples:

@env0:
    .byte $00,$c0,$7f,$00,$02
@env1:
    .byte $00,$cf,$7f,$00,$02
@env2:
    .byte $c0,$7f,$00,$01
@env3:
    .byte $7f,$00,$00

@tempo_env_1_mid:
    .byte $03,$05,$80

@song0ch0:
@song0ch0loop:
    .byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref5:
    .byte $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47
    .byte $41, $0c
    .word @song0ref5
    .byte $47
    .byte $41, $0c
    .word @song0ref5
    .byte $47
    .byte $41, $0c
    .word @song0ref5
    .byte $42
    .word @song0ch0loop
@song0ch1:
@song0ch1loop:
    .byte $80
@song0ref37:
    .byte $25, $91, $00
@song0ref40:
    .byte $b9
@song0ref41:
    .byte $27, $91, $00, $b9, $25, $8f, $00, $93, $25, $8f, $00, $93, $29, $8f, $00, $93, $29, $8f, $00, $93, $ff, $ff, $bf, $25
    .byte $91, $00, $91, $25, $91, $00, $91
    .byte $41, $17
    .word @song0ref41
    .byte $ff, $ff, $bf, $ff, $ff, $bf
    .byte $41, $23
    .word @song0ref37
    .byte $41, $1a
    .word @song0ref41
    .byte $41, $20
    .word @song0ref40
    .byte $41, $17
    .word @song0ref41
    .byte $ff, $ff, $bf, $ff, $ff, $bf, $42
    .word @song0ch1loop
@song0ch2:
@song0ch2loop:
    .byte $80
@song0ref104:
    .byte $1b, $c1, $00, $d9, $19, $c1, $00, $9d, $19, $8f, $00, $81, $1b, $8d, $00, $19, $87, $00, $87
    .byte $41, $13
    .word @song0ref104
    .byte $41, $13
    .word @song0ref104
    .byte $41, $13
    .word @song0ref104
    .byte $ff, $ff, $bf
    .byte $41, $13
    .word @song0ref104
    .byte $41, $13
    .word @song0ref104
    .byte $41, $13
    .word @song0ref104
    .byte $41, $13
    .word @song0ref104
    .byte $41, $13
    .word @song0ref104
    .byte $41, $13
    .word @song0ref104
    .byte $41, $13
    .word @song0ref104
    .byte $41, $13
    .word @song0ref104
    .byte $41, $13
    .word @song0ref104
    .byte $41, $13
    .word @song0ref104
    .byte $41, $13
    .word @song0ref104
    .byte $42
    .word @song0ch2loop
@song0ch3:
@song0ch3loop:
    .byte $80
@song0ref173:
    .byte $24, $91, $00, $91, $24, $87, $00, $9b, $22, $91, $00, $a5, $22, $89, $00, $85, $24, $91, $00, $91, $24, $87, $00, $9b
    .byte $22, $8f, $00, $bb
    .byte $41, $1c
    .word @song0ref173
    .byte $41, $1c
    .word @song0ref173
    .byte $41, $1c
    .word @song0ref173
    .byte $41, $1c
    .word @song0ref173
    .byte $41, $1c
    .word @song0ref173
    .byte $41, $1c
    .word @song0ref173
    .byte $41, $1c
    .word @song0ref173
    .byte $41, $1c
    .word @song0ref173
    .byte $41, $1c
    .word @song0ref173
    .byte $41, $1c
    .word @song0ref173
    .byte $41, $1c
    .word @song0ref173
    .byte $41, $1c
    .word @song0ref173
    .byte $41, $1c
    .word @song0ref173
    .byte $41, $1c
    .word @song0ref173
    .byte $41, $1c
    .word @song0ref173
    .byte $42
    .word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref250:
    .byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
    .byte $41, $0c
    .word @song0ref250
    .byte $41, $0c
    .word @song0ref250
    .byte $41, $0c
    .word @song0ref250
    .byte $42
    .word @song0ch4loop
