; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_pickup
	.word @sfx_ntsc_knife
	.word @sfx_ntsc_damage
	.word @sfx_ntsc_hammer
	.word @sfx_ntsc_inventory_full

@sfx_ntsc_pickup:
	.byte $82,$01,$81,$a2,$80,$3f,$89,$f0,$01,$81,$80,$01,$81,$5e,$01,$81
	.byte $3c,$01,$81,$1a,$01,$82,$00,$81,$f8,$01,$81,$d6,$01,$81,$b4,$01
	.byte $81,$92,$01,$81,$70,$01,$80,$30,$0a,$81,$92,$80,$3f,$01,$81,$b4
	.byte $01,$81,$d6,$01,$81,$f8,$01,$82,$01,$81,$1a,$01,$81,$3c,$01,$81
	.byte $5e,$01,$81,$80,$01,$81,$a2,$01,$81,$c4,$01,$00
@sfx_ntsc_knife:
	.byte $8a,$0a,$89,$3f,$01,$8a,$09,$01,$8a,$08,$01,$8a,$07,$01,$8a,$06
	.byte $01,$00
@sfx_ntsc_damage:
	.byte $8a,$0d,$89,$3f,$01,$8a,$0e,$02,$8a,$0f,$02,$00
@sfx_ntsc_hammer:
	.byte $89,$f0,$05,$8a,$0e,$89,$3f,$02,$8a,$0d,$02,$8a,$0c,$01,$00
@sfx_ntsc_inventory_full:
	.byte $87,$3a,$88,$02,$86,$8f,$89,$f0,$05,$86,$80,$05,$87,$80,$86,$8f
	.byte $0a,$00

.export sounds
