; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_pickup
	.word @sfx_ntsc_knife
	.word @sfx_ntsc_damage
	.word @sfx_ntsc_hammer
	.word @sfx_ntsc_inventory_full
	.word @sfx_ntsc_quest_complete
	.word @sfx_ntsc_weapon_breaks
	.word @sfx_ntsc_hp_up
	.word @sfx_ntsc_eat
	.word @sfx_ntsc_burn
	.word @sfx_ntsc_cook

@sfx_ntsc_pickup:
	.byte $81,$a2,$82,$01,$80,$3f,$89,$f0,$01,$81,$80,$01,$81,$5e,$01,$81
	.byte $3c,$01,$81,$1a,$01,$81,$f8,$82,$00,$01,$81,$d6,$01,$81,$b4,$01
	.byte $81,$92,$01,$81,$70,$01,$80,$30,$0a,$81,$92,$80,$3f,$01,$81,$b4
	.byte $01,$81,$d6,$01,$81,$f8,$01,$81,$1a,$82,$01,$01,$81,$3c,$01,$81
	.byte $5e,$01,$81,$80,$01,$81,$a2,$01,$81,$c4,$01,$00
@sfx_ntsc_knife:
	.byte $8a,$0a,$89,$3f,$01,$8a,$09,$01,$8a,$08,$01,$8a,$07,$01,$8a,$06
	.byte $01,$00
@sfx_ntsc_damage:
	.byte $8a,$0d,$89,$3f,$01,$8a,$0e,$02,$8a,$0f,$02,$00
@sfx_ntsc_hammer:
	.byte $89,$f0,$05,$8a,$0e,$89,$3f,$02,$8a,$0d,$02,$8a,$0c,$01,$00
@sfx_ntsc_inventory_full:
	.byte $87,$3a,$88,$02,$86,$8f,$89,$f0,$05,$86,$80,$05,$87,$80,$86,$8f
	.byte $0a,$00
@sfx_ntsc_quest_complete:
	.byte $81,$fd,$82,$00,$80,$3f,$89,$f0,$05,$81,$e1,$05,$81,$fd,$05,$81
	.byte $e1,$05,$81,$fd,$05,$81,$e1,$05,$81,$fd,$05,$81,$e1,$05,$00
@sfx_ntsc_weapon_breaks:
	.byte $8a,$0b,$89,$3f,$03,$8a,$0c,$03,$8a,$0d,$03,$8a,$0e,$03,$8a,$0f
	.byte $04,$8a,$00,$03,$8a,$01,$03,$8a,$02,$08,$00
@sfx_ntsc_hp_up:
	.byte $81,$b2,$82,$00,$80,$3f,$89,$f0,$01,$81,$90,$01,$81,$6d,$01,$81
	.byte $4b,$01,$80,$30,$01,$81,$a4,$80,$3f,$01,$81,$8b,$01,$81,$72,$01
	.byte $81,$59,$01,$81,$42,$01,$80,$30,$01,$81,$8c,$80,$3f,$01,$81,$70
	.byte $01,$81,$53,$01,$81,$38,$01,$00
@sfx_ntsc_eat:
	.byte $81,$d5,$82,$00,$80,$3f,$89,$f0,$02,$80,$30,$01,$81,$bd,$80,$3f
	.byte $02,$80,$30,$01,$81,$a9,$80,$3f,$02,$80,$30,$01,$81,$9f,$80,$3f
	.byte $02,$00
@sfx_ntsc_burn:
	.byte $8a,$05,$89,$3f,$03,$8a,$03,$04,$8a,$01,$09,$00
@sfx_ntsc_cook:
	.byte $8a,$03,$89,$3f,$03,$8a,$04,$07,$8a,$03,$14,$00

.export sounds
